// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlttglkptuhwmscmlaau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdHRnbGtwdHVod21zY21sYWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjM4NDMsImV4cCI6MjA1OTU5OTg0M30.ThgHFwpkS4YLuWRevdh1UMJpxzrRFTy3JbxEWp7ABWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);